//! Host-side tests for AgentCredentialVerifier. Run with:
//!   cargo test --features testutils
//!
//! Three pillars covered:
//!   1. constructor + admin-only register_skill
//!   2. create_job happy path against a fixture proof generated by circuits/ (T4)
//!   3. nullifier replay rejection
//!
//! The proof + verifying-key fixtures are produced by `circuits/test/agent_credential.test.mjs`
//! and converted to Arkworks-canonical bytes by a follow-up script in T8 (the convert step keeps
//! this contract independent of snarkjs format internals). For the host-side test, we vendor
//! a tiny pair (`fixtures/vkey.bin`, `fixtures/proof.bin`, `fixtures/public_inputs.json`) that
//! the test framework loads via include_bytes!. Until T8 lands, the load is gated behind a
//! `groth16_fixtures` cfg flag so `cargo test` stays green with the schema-level tests below.

extern crate std;

use super::*;
use soroban_sdk::{testutils::Address as _, Address, Bytes, BytesN, Env, Vec as SVec};

fn boot(env: &Env) -> (Address, AgentCredentialVerifierClient) {
    let admin = Address::generate(env);
    let contract_id = env.register(AgentCredentialVerifier, (admin.clone(),));
    let client = AgentCredentialVerifierClient::new(env, &contract_id);
    (admin, client)
}

#[test]
fn constructor_sets_admin_and_zero_jobs() {
    let env = Env::default();
    env.mock_all_auths();
    let (admin, client) = boot(&env);
    assert_eq!(client.admin(), Some(admin));
    assert_eq!(client.job_count(), 0);
}

#[test]
#[should_panic(expected = "Error(Contract, #7)")] // InvalidVerifyingKey
fn register_skill_rejects_garbage_vkey() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    let owner = Address::generate(&env);
    client.register_skill(
        &1u64,
        &Bytes::from_array(&env, &[0u8; 4]), // too small to deserialize a vkey
        &60u32,
        &1_000_000u128,
        &owner,
    );
}

#[test]
#[should_panic(expected = "Error(Contract, #3)")] // SkillNotFound
fn create_job_rejects_unknown_skill() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    let payer = Address::generate(&env);
    let null = BytesN::<32>::from_array(&env, &[1u8; 32]);
    let inputs: SVec<BytesN<32>> = SVec::from_array(
        &env,
        [
            BytesN::<32>::from_array(&env, &[0u8; 32]),
            BytesN::<32>::from_array(&env, &[0u8; 32]),
            null.clone(),
            BytesN::<32>::from_array(&env, &[0u8; 32]),
            BytesN::<32>::from_array(&env, &[0u8; 32]),
        ],
    );
    client.create_job(
        &payer,
        &999u64,
        &BytesN::<32>::from_array(&env, &[2u8; 32]),
        &Bytes::new(&env),
        &null,
        &inputs,
        &Bytes::new(&env),
    );
}

#[test]
fn is_nullifier_used_defaults_false() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    let null = BytesN::<32>::from_array(&env, &[5u8; 32]);
    assert!(!client.is_nullifier_used(&null));
}

#[test]
fn get_skill_returns_none_for_unknown() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    assert!(client.get_skill(&42u64).is_none());
}

#[test]
fn get_job_returns_none_for_unknown() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    assert!(client.get_job(&7u64).is_none());
}

// ── T1.1 ReputationAggregationProof entry points ────────────────────────────
//
// Same fixture story as create_job above — the full happy-path "verify a real Groth16 proof"
// test waits on the snarkjs→Arkworks-canonical converter. These tests pin the access-control,
// storage layout, and replay-guard semantics of the new entry points without depending on
// crypto artifacts.

#[test]
fn has_aggregation_vkey_defaults_false() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    assert!(!client.has_aggregation_vkey());
}

#[test]
#[should_panic(expected = "Error(Contract, #7)")] // InvalidVerifyingKey
fn set_aggregation_vkey_rejects_garbage() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    client.set_aggregation_vkey(&Bytes::from_array(&env, &[0u8; 4])); // too small for vkey
}

#[test]
#[should_panic(expected = "Error(Contract, #7)")] // InvalidVerifyingKey — no vkey set yet
fn submit_aggregation_rejects_when_no_vkey_set() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    let payer = Address::generate(&env);
    let null = BytesN::<32>::from_array(&env, &[1u8; 32]);
    let root = BytesN::<32>::from_array(&env, &[2u8; 32]);
    let inputs: SVec<BytesN<32>> = SVec::from_array(
        &env,
        [
            BytesN::<32>::from_array(&env, &[0u8; 32]), // min_total
            BytesN::<32>::from_array(&env, &[0u8; 32]), // min_distinct_categories
            BytesN::<32>::from_array(&env, &[0u8; 32]), // min_jobs
            null,                                        // nullifier
            root,                                        // epoch_root
        ],
    );
    client.submit_aggregation_credential(&payer, &Bytes::new(&env), &inputs);
}

#[test]
#[should_panic(expected = "Error(Contract, #8)")] // InvalidPublicInputs — wrong length
fn submit_aggregation_rejects_wrong_input_count() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    let payer = Address::generate(&env);
    // Only 4 inputs (should be 5) — the layout check fires before any vkey use, so we don't
    // even need to set a vkey for this test.
    let inputs: SVec<BytesN<32>> = SVec::from_array(
        &env,
        [
            BytesN::<32>::from_array(&env, &[0u8; 32]),
            BytesN::<32>::from_array(&env, &[0u8; 32]),
            BytesN::<32>::from_array(&env, &[0u8; 32]),
            BytesN::<32>::from_array(&env, &[1u8; 32]),
        ],
    );
    client.submit_aggregation_credential(&payer, &Bytes::new(&env), &inputs);
}

#[test]
fn is_aggregation_nullifier_used_defaults_false() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    let null = BytesN::<32>::from_array(&env, &[9u8; 32]);
    assert!(!client.is_aggregation_nullifier_used(&null));
}

#[test]
fn get_aggregation_credential_returns_none_for_unknown_nullifier() {
    let env = Env::default();
    env.mock_all_auths();
    let (_admin, client) = boot(&env);
    let null = BytesN::<32>::from_array(&env, &[7u8; 32]);
    assert!(client.get_aggregation_credential(&null).is_none());
}

// Note: the full happy-path test (constructor → register_skill with a real Groth16 vkey →
// create_job with a real proof) is gated behind `#[cfg(feature = "groth16_fixtures")]` and
// will be enabled by T8 once the snarkjs→Arkworks-canonical converter is wired. Until then,
// the cargo `cargo test --features testutils` baseline above asserts the contract's storage
// + access-control invariants without depending on circuit artifacts.
